Insert Into Motiv ( motiv_id, naziv) Values ( 1,'Still life (mrtva priroda)' );
Insert Into Motiv ( motiv_id, naziv) Values ( 2,'Ekologija i priroda' );
Insert Into Motiv ( motiv_id, naziv) Values ( 3,'Surrealizam' );
Insert Into Motiv ( motiv_id, naziv) Values ( 4,'Impresionizam' );
Insert Into Motiv ( motiv_id, naziv) Values ( 5,'Melankolija' );
Insert Into Motiv ( motiv_id, naziv) Values ( 6,'Djeca' );
Insert Into Motiv ( motiv_id, naziv) Values ( 7,'Urbani motivi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 8,'Moda' );
Insert Into Motiv ( motiv_id, naziv) Values ( 9,'Impresionizam' );
Insert Into Motiv ( motiv_id, naziv) Values ( 10,'Znanost i tehnologija' );
Insert Into Motiv ( motiv_id, naziv) Values ( 11,'Psihologija i unutarnji svijet' );
Insert Into Motiv ( motiv_id, naziv) Values ( 12,'Urbani motivi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 13,'Ekologija i priroda' );
Insert Into Motiv ( motiv_id, naziv) Values ( 14,'Alegorije' );
Insert Into Motiv ( motiv_id, naziv) Values ( 15,'Industrijski motivi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 16,'Ekologija i priroda' );
Insert Into Motiv ( motiv_id, naziv) Values ( 17,'Humor' );
Insert Into Motiv ( motiv_id, naziv) Values ( 18,'Glazba' );
Insert Into Motiv ( motiv_id, naziv) Values ( 19,'Sloboda' );
Insert Into Motiv ( motiv_id, naziv) Values ( 20,'Ples' );
Insert Into Motiv ( motiv_id, naziv) Values ( 21,'inkluzija' );
Insert Into Motiv ( motiv_id, naziv) Values ( 22,'Sport' );
Insert Into Motiv ( motiv_id, naziv) Values ( 23,'Djeca' );
Insert Into Motiv ( motiv_id, naziv) Values ( 24,'Pejzaži ' );
Insert Into Motiv ( motiv_id, naziv) Values ( 25,'Kultura i tradicija' );
Insert Into Motiv ( motiv_id, naziv) Values ( 26,'Aktovi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 27,'Ratni motivi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 28,'Impresionizam' );
Insert Into Motiv ( motiv_id, naziv) Values ( 29,'Snovi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 30,'Društvene nepravde' );
Insert Into Motiv ( motiv_id, naziv) Values ( 31,'Religiozni motivi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 32,'Snovi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 33,'Sezonski motivi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 34,'Mitološki motivi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 35,'Društvene nepravde' );
Insert Into Motiv ( motiv_id, naziv) Values ( 36,'Politika i socijalne teme' );
Insert Into Motiv ( motiv_id, naziv) Values ( 37,'Hrana i gastronomija' );
Insert Into Motiv ( motiv_id, naziv) Values ( 38,'Glazba' );
Insert Into Motiv ( motiv_id, naziv) Values ( 39,'Znanost i tehnologija' );
Insert Into Motiv ( motiv_id, naziv) Values ( 40,'Snovi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 41,'Alegorije' );
Insert Into Motiv ( motiv_id, naziv) Values ( 42,'Aktovi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 43,'Ekspresionizam' );
Insert Into Motiv ( motiv_id, naziv) Values ( 44,'Snovi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 45,'Feminizam' );
Insert Into Motiv ( motiv_id, naziv) Values ( 46,'Religiozni motivi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 47,'Religiozni motivi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 48,'Impresionizam' );
Insert Into Motiv ( motiv_id, naziv) Values ( 49,'Snovi' );
Insert Into Motiv ( motiv_id, naziv) Values ( 50,'Surrealizam' );
